sudo: required
dist: trusty
language: python

python:
    - 2.7
    - 3.5
    - 3.6

script:
  - pip install .
  - cd tests
  - python setup.py build
  - python setup.py install
  - mkdir test_run
  - cp run_tests.py test_run/.
  - cd test_run
  - python run_tests.py
